spring.datasource.url=jdbc:postgresql://localhost:5432/SawaSkills
spring.datasource.username=your_username
spring.datasource.password=your_password

spring.jpa.hibernate.ddl-auto=update

jwt.secret=YOUR_SECRET_KEY

resend.api.key=YOUR_RESEND_KEY